import Image from "next/image";

export default function AboutPage() {
    return (
        <main className="relative min-h-screen w-full bg-[#051C22] text-[#f8fafc] flex flex-col items-center justify-center overflow-hidden font-serif">

            {/* --- LAYER 1: BACKGROUND GLOW --- */}
            <div className="absolute bottom-[-15%] left-1/2 -translate-x-1/2 w-[120%] h-[50%] bg-[#E5B96F] opacity-15 blur-[120px] rounded-[100%] pointer-events-none" />

            {/* --- LAYER 2: ORNATE FRAME SVG --- */}
            <div className="absolute inset-0 pointer-events-none z-10 flex items-center justify-center p-2 md:p-6">
                <Image
                    src="/background.svg"
                    alt="Decorative Frame"
                    fill
                    className="object-fill"
                    priority
                />
            </div>

            {/* --- LAYER 3: VIGNETTE --- */}
            <div className="absolute inset-0 pointer-events-none bg-[radial-gradient(circle_at_center,_transparent_30%,_#000000_120%)] z-10" />

            {/* Main Content Container */}
            <div className="relative z-20 w-full max-w-[90rem] min-h-screen flex flex-col p-8 md:p-12">

                {/* Header - Centered Title */}
                <div className="flex justify-center w-full mt-8 md:mt-12 mb-8 shrink-0">
                    <h1
                        className="text-metallic text-6xl md:text-8xl font-bold tracking-widest uppercase text-center"
                        style={{
                            WebkitTextStroke: '1px rgba(229, 185, 111, 0.3)',
                            filter: 'drop-shadow(0 4px 4px rgba(0,0,0,0.5))'
                        }}
                    >
                        ABOUT
                    </h1>
                </div>

                {/* Content Body */}
                <div className="flex flex-1 flex-col md:flex-row items-center justify-center gap-8 w-full pb-8 md:pb-16 relative">

                    {/* Left Side - Guide Woman */}
                    <div className="w-full md:w-1/2 h-[50vh] md:h-[70vh] relative flex items-center justify-center">
                        <div className="relative w-full h-full">
                            <Image
                                src="/guideWomen.svg"
                                alt="Guide"
                                fill
                                className="object-contain"
                                priority
                            />
                        </div>
                    </div>

                    {/* Right Side - Text Content */}
                    <div className="w-full md:w-1/2 flex flex-col justify-center items-center md:items-start text-center md:text-left space-y-6 px-4 md:pr-12 max-w-2xl">
                        <div className="prose prose-invert prose-lg text-[#E5B96F]/80 leading-relaxed space-y-6 backdrop-blur-md bg-black/40 p-10 rounded-2xl border border-[#E5B96F]/20 shadow-[0_0_30px_rgba(0,0,0,0.5)]">
                            <p className="text-xl font-light text-[#E5B96F]">
                                <span className="font-bold text-metallic">AI Nexus</span> invites you to a world where ancient legends meet futuristic intelligence.
                            </p>
                            <p>
                                Guided by the keepers of knowledge, explore a universe generated by the most advanced algorithms, yet rooted in the timeless art of storytelling.
                            </p>
                            <p className="italic text-[#E5B96F]/60">
                                "The only limit is your imagination."
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    );
}
