import { motion } from "framer-motion";
import Image from "next/image";

interface AboutViewProps {
    onBack: () => void;
}

export const AboutView = ({ onBack }: AboutViewProps) => {
    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="relative z-20 w-full flex flex-col p-4 md:p-8"
        >
            {/* Header - Centered Title */}
            <div className="flex justify-center w-full mt-4 mb-8 shrink-0">
                <h1
                    className="text-metallic text-4xl md:text-6xl font-bold tracking-widest uppercase text-center"
                    style={{
                        WebkitTextStroke: '1px rgba(229, 185, 111, 0.3)',
                        filter: 'drop-shadow(0 4px 4px rgba(0,0,0,0.5))'
                    }}
                >
                    ABOUT
                </h1>
            </div>

            {/* Content Body */}
            <div className="flex flex-1 flex-col md:flex-row items-center justify-center gap-8 w-full pb-8 relative">

                {/* Left Side - Guide Woman */}
                <div className="w-full md:w-1/2 h-[40vh] md:h-[60vh] relative flex items-center justify-center">
                    <div className="relative w-full h-full">
                        <Image
                            src="/guideWomen.svg"
                            alt="Guide"
                            fill
                            className="object-contain"
                            priority
                        />
                    </div>
                </div>

                {/* Right Side - Text Content */}
                <div className="w-full md:w-1/2 flex flex-col justify-center items-center md:items-start text-center md:text-left space-y-6 px-4 md:pr-12 max-w-xl">
                    <div className="prose prose-invert prose-lg text-[#E5B96F]/80 leading-relaxed space-y-6 backdrop-blur-md bg-black/40 p-6 md:p-10 rounded-2xl border border-[#E5B96F]/20 shadow-[0_0_30px_rgba(0,0,0,0.5)]">
                        <p className="text-lg md:text-xl font-light text-[#E5B96F]">
                            <span className="font-bold text-metallic">AI Nexus</span> invites you to a world where ancient legends meet futuristic intelligence.
                        </p>
                        <p className="text-base md:text-lg">
                            Guided by the keepers of knowledge, explore a universe generated by the most advanced algorithms, yet rooted in the timeless art of storytelling.
                        </p>
                        <p className="italic text-[#E5B96F]/60 text-base">
                            "The only limit is your imagination."
                        </p>
                    </div>
                </div>
            </div>

            {/* Back Button - Centered at Bottom */}
            <div className="flex justify-center w-full mt-4">
                <button
                    onClick={onBack}
                    className="text-[#E5B96F]/40 hover:text-[#E5B96F] text-sm tracking-widest uppercase transition-colors py-2"
                >
                    Back to Menu
                </button>
            </div>
        </motion.div>
    );
};
